# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-21 10:48
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('teacher_name', models.CharField(max_length=200)),
                ('teacher_email', models.EmailField(max_length=120)),
                ('subscribers', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='subscribers')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2200)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2016, 8, 21, 10, 48, 55, 208417, tzinfo=utc))),
                ('end_date', models.DateTimeField(blank=True, default='', null=True)),
                ('event_duration', models.CharField(blank=True, max_length=200, null=True, verbose_name='Duration (optional)')),
                ('classroom', models.ManyToManyField(to='event.Classroom')),
            ],
        ),
    ]
