# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 14:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(max_length=200)),
                ('created', models.DateTimeField(default=datetime.datetime(2016, 5, 26, 14, 37, 55, 930197, tzinfo=utc))),
                ('event', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('teacher_name', models.CharField(max_length=200)),
                ('teacher_email', models.EmailField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2200)),
                ('location', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField(default=datetime.datetime(2016, 5, 26, 14, 37, 55, 927720, tzinfo=utc))),
                ('event_length', models.IntegerField(max_length=200)),
                ('classroom', models.ManyToManyField(to='event.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('child_name', models.CharField(max_length=200)),
                ('classrooms', models.CharField(max_length=200)),
                ('created', models.DateTimeField(default=datetime.datetime(2016, 5, 26, 14, 37, 55, 929675, tzinfo=utc))),
            ],
        ),
    ]
