# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-30 11:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.CharField(blank=True, default='pta', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 30, 11, 13, 33, 214686, tzinfo=utc)),
        ),
    ]
