# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 18:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20160526_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 18, 45, 58, 420808, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 18, 45, 58, 418502, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='parent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 18, 45, 58, 420290, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='classroom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Classroom'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
