# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 18:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20160526_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='classroom_id',
            new_name='classroom',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='activity',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 18, 50, 57, 475410, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 18, 50, 57, 473116, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='parent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 18, 50, 57, 474897, tzinfo=utc)),
        ),
    ]
