# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 21:59
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0004_auto_20160526_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='participants'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 21, 59, 40, 285568, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 21, 59, 40, 283455, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='parent',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 21, 59, 40, 285067, tzinfo=utc)),
        ),
    ]
