# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 23:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20160526_2159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 23, 33, 7, 251562, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
