# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 23:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0006_auto_20160526_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='participants',
        ),
        migrations.AddField(
            model_name='classroom',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='subscribers'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 26, 23, 42, 41, 902363, tzinfo=utc)),
        ),
    ]
