# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-28 10:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20160527_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 28, 10, 6, 19, 998149, tzinfo=utc)),
        ),
    ]
