# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 10:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_auto_20160529_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 29, 10, 24, 8, 600840, tzinfo=utc)),
        ),
    ]
