# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-18 10:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_auto_20160529_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 18, 10, 6, 25, 997565, tzinfo=utc)),
        ),
    ]
